---
root: true

parserOptions:
  ecmaVersion: latest
  sourceType: module

env:
  es2021: true
  browser: true

extends:
  - 'airbnb-base'

rules:
  no-console: 0
  import/extensions: 0
  no-param-reassign: 0
